location / {
      root /data/html/garage-landing;
      index index.html;
      try_files $uri $uri/ /index.html;
  }
location = /robots.txt {
      root /data/html/garage-landing;                                                                                                                                                                                                                                                                                      
      log_not_found off;                                                                                                                                                                                                                                                                                                   
      access_log off;
  }

location = /sitemap.xml {
    root /data/html/garage-landing;
    log_not_found off;
    access_log off;
}
